# Generated by Django 5.1.6 on 2025-03-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modela',
            name='multiselect_utf8',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
